name: Documentation

on:
  push:
    branches: [ main ]
      
jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      env:
        runner: self-hosted
      with:
        php-version: '8.1'
        extensions: mbstring, dom, intl, iconv
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Generate documentation
      run: vendor/bin/daux generate
    - name: Upload files to Object Storage
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete 
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
        SOURCE_DIR: 'static'
